-- SQLite

CREATE TABLE CUSTOMER (
    ID          INTEGER         PRIMARY KEY AUTOINCREMENT,
    NAME        VARCHAR(128),
    LASTNAME    VARCHAR(155),
    PHONE       VARCHAR(16),
    EMAIL       VARCHAR(32),
    ADDRESS     VARCHAR(200),
    CITY        VARCHAR(64),
    STATE       VARCHAR(2),
    BIRTH_DATE  DATETIME
);