-- SQLite

CREATE TABLE EMPLOYEES (
    ID              INTEGER         PRIMARY KEY AUTOINCREMENT,
    NAME            VARCHAR(100),
    PHONE           VARCHAR(16),
    CONTRACT_DATE   DATETIME,
    POSITION_ID     INTEGER,

    FOREIGN KEY (POSITION_ID) REFERENCES POSITIONS(ID)
);