-- SQLite

CREATE TABLE CARS (
    ID       INTEGER        PRIMARY KEY AUTOINCREMENT,
    NAME     VARCHAR(120),
    YEAR     INTEGER,
    COLOR    VARCHAR(32),
    KM       FLOAT(10,2),
    STATUS   VARCHAR(17),
    BRAND_ID INTEGER,
    MODEL_ID INTEGER,

    FOREIGN KEY (BRAND_ID) REFERENCES CAR_BRANDS (ID),
    FOREIGN KEY (MODEL_ID) REFERENCES CAR_MODELS (ID)
);