-- SQLite

CREATE TABLE LOCATIONS (
    ID          INTEGER     PRIMARY KEY AUTOINCREMENT,
    START_DATE  DATETIME,
    END_DATE    DATETIME,
    TOTAL       FLOAT(10,2),
    CUSTOMER_ID INTEGER,
    CAR_ID      INTEGER,
    EMPLOYEE_ID INTEGER,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER (ID),
    FOREIGN KEY (CAR_ID) REFERENCES CARS (ID),
    FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (ID)
);